version: 2

before:
  hooks:
    - go mod download

changelog:
  sort: desc
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - Merge branch
      - Merge pull request

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
    main: ./
    binary: kyx
    ldflags: -s -w -X 'main.channel={{ if index .Env "AUTOUPDATE_CHANNEL" }}{{ .Env.AUTOUPDATE_CHANNEL }}{{ else }}dev{{ end }}' -X 'main.buildDate={{ .Date }}' -X 'main.version={{ .Version }}'
    flags:
        - -trimpath

archives:
    - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
      files:
          - README.md
          - LICENSE
checksum:
    name_template: 'checksums.txt'

source:
    enabled: true

snapshot:
    version_template: "next"

universal_binaries:
    - replace: true
      name_template: kyx

release:
    footer: |
        **Full Changelog**: https://github.com/SoureCode/kyx/compare/{{ .PreviousTag }}...{{ .Tag }}